### ISSUE TITLE
Error ROS agent in Habitat

### ISSUE THREAD

**Issue by JulioPlaced** [ericchen321/ros_x_habitat#19]
When running the ROS agent in habitat (src/scripts/roam_with_joy.py ), I'm getting the following error:

`Traceback (most recent call last):
  File "src/nodes/habitat_env_node.py", line 709, in <module>
    main()
  File "src/nodes/habitat_env_node.py", line 705, in main
    env_node.simulate()
  File "src/nodes/habitat_env_node.py", line 637, in simulate
    self.reset()
  File "src/nodes/habitat_env_node.py", line 266, in reset
    self.observations = self.env.reset()
  File "/home/user/miniconda3/envs/habitat/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/.../src/ros_x_habitat/src/envs/habitat_rlenv.py", line 73, in reset
    return self._env.reset()
  File "/.../src/ros_x_habitat/src/envs/physics_env.py", line 176, in reset
    obj.motion_type = hsim.physics.MotionType.DYNAMIC
AttributeError: 'NoneType' object has no attribute 'motion_type'
`

Any ideas?

**Comment by JulioPlaced** [comment]
Closing as duplicate
