### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'motion_type'

### ISSUE THREAD

**Issue by SepMJ** [ericchen321/ros_x_habitat#24]
The command is：
python src/scripts/eval_and_vis_habitat.py --input-type rgbd --model-path data/checkpoints/v2/gibson-rgbd-best.pth --task-config   configs/setting_4_configs/pointnav_rgbd-mp3d.yaml --episode-id  -1 --seed-file-path  seeds/seed=7.csv --log-dir  logs/ --make-maps --map-dir habitat_maps/  --make-plots \

Traceback (most recent call last):
  File "src/scripts/eval_and_vis_habitat.py", line 169, in <module>
    main()
  File "src/scripts/eval_and_vis_habitat.py", line 99, in main
    map_height=200,
  File "/home/duansh/rosxhab/catkin_ws/src/ros_x_habitat/src/evaluators/habitat_evaluator.py", line 125, in evaluate_and_get_maps
    observations_per_action = self.env.reset()
  File "/home/duansh/anaconda3/envs/rosxhab2/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/duansh/rosxhab/catkin_ws/src/ros_x_habitat/src/envs/habitat_rlenv.py", line 73, in reset
    return self._env.reset()
  File "/home/duansh/rosxhab/catkin_ws/src/ros_x_habitat/src/envs/physics_env.py", line 176, in reset
    obj.motion_type = hsim.physics.MotionType.DYNAMIC
AttributeError: 'NoneType' object has no attribute 'motion_type'

I haven't found a solution. Can I ask if there is any way? Thank you

**Comment by ericchen321** [comment]
Hi @jiaomengzhang sorry about the late reply. I've been swamped by other projects lately.

I hope you've solved it but in case you haven't, looks like someone suggested had the same problem a solution [here](https://github.com/ericchen321/ros_x_habitat/issues/12#issuecomment-1479231894). I tried removing `default.physics_config.json` and was able to reproduce the error. You can download the file from [this link](https://github.com/facebookresearch/habitat-sim/blob/v0.2.0/data/default.physics_config.json).
