### ISSUE TITLE
ImportError: cannot import name 'Roam"

### ISSUE THREAD

**Issue by marcopremigit** [ericchen321/ros_x_habitat#8]
Hi and thank you for your work!
I'm trying to run the example `Navigating ROS Agent in Habitat Sim`, with:
`python ros_x_habitat/src/scripts/roam_with_joy.py --hab-env-config-path ros_x_habitat/configs/roam_configs/pointnav_rgbd_roam_mp3d_test_scenes.yaml --episode-id 1 --scene-id data/scene_datasets/mp3d/2t7WUuJeko7/2t7WUuJeko7.glb --video-frame-period 24`
but I have this error:
`Traceback (most recent call last):
  File "/home/marco/catkin_ws/src/ros_x_habitat/src/scripts/roam_with_joy.py", line 2, in <module>
    from src.roamers.joy_habitat_roamer import JoyHabitatRoamer
  File "/home/marco/catkin_ws/src/ros_x_habitat/src/roamers/joy_habitat_roamer.py", line 6, in <module>
    from ros_x_habitat.srv import Roam
ImportError: cannot import name 'Roam' from 'ros_x_habitat.srv' (unknown location)
`
If I add `__init__.py` in the srv folder, the error becomes: 
`ImportError: cannot import name 'Roam' from 'ros_x_habitat.srv' (/home/marco/catkin_ws/src/ros_x_habitat/srv/__init__.py)`
Do you have any ideas why I'm having this issue?

**Comment by marcopremigit** [comment]
It was only a problem of pythonpath.
